name: Aws Test

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 🚀 Deploy code every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: ./
        with:
          server: ftp://54.243.9.150
          username: fahad
          password: ${{ secrets.ftp_password }}
          protocol: ftp
